# Generated by Django 4.2.1 on 2023-05-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
