# Generated by Django 4.2.1 on 2023-05-18 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_post_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_like',
            field=models.ManyToManyField(related_name='users_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
