# Generated by Django 4.2.1 on 2023-05-18 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_remove_post_users_like_favoritebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteBook',
            new_name='Favoritepost',
        ),
    ]
