# Generated by Django 4.2.1 on 2023-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_favoritebook_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content_grad',
            field=models.TextField(blank=True),
        ),
    ]
